services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io:latest
    container_name: changedetection
    volumes:
      - changedetection-data:/datastore
    ports:
      - "5000:5000"
    environment:
      - PLAYWRIGHT_DRIVER_URL=ws://playwright-chrome:3000
    depends_on:
      - playwright-chrome
    restart: unless-stopped

  playwright-chrome:
    image: browserless/chrome
    container_name: playwright-chrome
    restart: unless-stopped

volumes:
  changedetection-data:
