networks:
  servarrnetwork:
    name: servarrnetwork
    ipam:
      config:
        - subnet: 172.39.0.0/24

services:

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - UMASK=002
    volumes:
      - ./qbittorrent:/config
      - /data:/data
    ports:
      - 8080:8080
      - 6881:6881
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.10

  #nzbget:
   # image: lscr.io/linuxserver/nzbget:latest
    #container_name: nzbget
    #environment:
     # - PUID=${PUID}
      #- PGID=${PGID}
      #- TZ=${TZ}
      #- UMASK=002
    #volumes:
      #- /etc/localtime:/etc/localtime:ro
      #- ./nzbget:/config
      #- /data:/data
    #ports:
      #- 6789:6789
    #restart: unless-stopped
    #networks:
      #servarrnetwork:
        #ipv4_address: 172.39.0.11

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.12

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./sonarr:/config
      - /data:/data
    ports:
      - 8989:8989
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.3

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./radarr:/config
      - /data:/data
    ports:
      - 7878:7878
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.4

  #lidarr:
    #container_name: lidarr
    #image: lscr.io/linuxserver/lidarr:latest
    #restart: unless-stopped
    #volumes:
     # - /etc/localtime:/etc/localtime:ro
     # - ./lidarr:/config
     # - /data:/data
    #environment:
     # - PUID=${PUID}
     # - PGID=${PGID}
     # - TZ=${TZ}
     # - UMASK=002
    #ports:
     # - 8686:8686
    #networks:
      #servarrnetwork:
        #ipv4_address: 172.39.0.5

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./bazarr:/config
      - /data:/data
    ports:
      - 6767:6767
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.6
