services:
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    restart: unless-stopped

    ports:
      - "1880:1880"

    environment:
      TZ: Europe/Bucharest

    volumes:
      - node_red_data:/data

volumes:
  node_red_data:
