services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - /docker/uptime-kuma/data:/app/data
    ports:
      - "3002:3001"

